/*
 * PS2HostCmds.h
 *
 * Created: 24.10.2015 08:33:48
 *  Author: Bernd
 */ 

#define PS2HOST_CMD_RESET 0xFF
#define PS2HOST_CMD_RESEND 0xFE
#define PS2HOST_CMD_SET_KEY_TYPE_MAKE 0xFD
#define PS2HOST_CMD_SET_KEY_TYPE_MAKE_BREAK 0xFC
#define PS2HOST_CMD_SET_KEY_TYPE_TYPEMATIC 0xFB
#define PS2HOST_CMD_SET_ALL_KEYS_TYPEMATIC_MAKE_BREAK 0xFA
#define PS2HOST_CMD_SET_ALL_KEYS_MAKE 0xF9
#define PS2HOST_CMD_SET_ALL_KEYS_MAKE_BREAK 0xF8
#define PS2HOST_CMD_SET_ALL_KEYS_TYPEMATIC 0xF7
#define PS2HOST_CMD_SET_DEFAULT 0xF6
#define PS2HOST_CMD_DISABLE 0xF5
#define PS2HOST_CMD_ENABLE 0xF4
#define PS2HOST_CMD_SET_TYPEMATIC_RATE_DELAY 0xF3
#define PS2HOST_CMD_READ_ID 0xF2
#define PS2HOST_CMD_SET_SCAN_CODE_SET 0xF0
#define PS2HOST_CMD_ECHO 0xEE
#define PS2HOST_CMD_SET_RESET_LEDS 0xED

#define PS2DEVICE_CMD_ACK 0xFA
#define PS2DEVICE_CMD_ECHO 0xEE
#define PS2DEVICE_CMD_RESEND 0xFE
#define PS2DEVICE_ID_1 0xAB
#define PS2DEVICE_ID_2 0x83
#define PS2DEVICE_BAT_OK 0xAA
#define PS2DEVICE_BAT_ERROR 0xFC